// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'menuitem-create-item-md'
  | 'menuitem-create-md'
  | 'menuitem-create-standalone-md'
  | 'menuitem-new-whiteboard'
  | 'menuitem-open-md'
  | 'pref-enable'
  | 'pref-font-size'
  | 'pref-frontmatter'
  | 'pref-help'
  | 'pref-shortcut-standalone'
  | 'pref-shortcut-standalone-help'
  | 'pref-title'
  | 'prefs-title'
  | 'startup-begin'
  | 'startup-finish'
  | 'whiteboard-tab-title'
  | 'whiteboard-open'
  | 'whiteboard-save'
  | 'whiteboard-saved'
  | 'whiteboard-save-failed'
  | 'whiteboard-open-failed'
  | 'whiteboard-unsaved-title'
  | 'whiteboard-unsaved-prompt'
  | 'whiteboard-add-item'
  | 'whiteboard-add-note'
  | 'whiteboard-add-pdf'
  | 'whiteboard-add-file';
